export const EDIT_NAME = 'EDIT_NAME'
export const EDIT_CODE = 'EDIT_CODE'
export const NEW_PIECE = 'NEW_PIECE'
export const MOVE_PIECE = 'MOVE_PIECE'
export const ANIMATION_STEP = 'ANIMATION_STEP'
export const ANIMATION_OVER = 'ANIMATION_OVER'
export const UPDATE_TETRIS = 'UPDATE_TETRIS'

export const START_GAME = 'server/START_GAME'
export const CREATE_ROOM = 'server/CREATE_ROOM'
export const JOIN_ROOM = 'server/JOIN_ROOM'
